// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace TheOmenDen.CorvidDelivery.Twitch.Users.Extensions {
    public class ExtensionsPutResponse_data : IAdditionalDataHolder, IParsable {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The component property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ExtensionsPutResponse_data_component? Component { get; set; }
#nullable restore
#else
        public ExtensionsPutResponse_data_component Component { get; set; }
#endif
        /// <summary>The overlay property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ExtensionsPutResponse_data_overlay? Overlay { get; set; }
#nullable restore
#else
        public ExtensionsPutResponse_data_overlay Overlay { get; set; }
#endif
        /// <summary>The panel property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ExtensionsPutResponse_data_panel? Panel { get; set; }
#nullable restore
#else
        public ExtensionsPutResponse_data_panel Panel { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="ExtensionsPutResponse_data"/> and sets the default values.
        /// </summary>
        public ExtensionsPutResponse_data() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="ExtensionsPutResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static ExtensionsPutResponse_data CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new ExtensionsPutResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"component", n => { Component = n.GetObjectValue<ExtensionsPutResponse_data_component>(ExtensionsPutResponse_data_component.CreateFromDiscriminatorValue); } },
                {"overlay", n => { Overlay = n.GetObjectValue<ExtensionsPutResponse_data_overlay>(ExtensionsPutResponse_data_overlay.CreateFromDiscriminatorValue); } },
                {"panel", n => { Panel = n.GetObjectValue<ExtensionsPutResponse_data_panel>(ExtensionsPutResponse_data_panel.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<ExtensionsPutResponse_data_component>("component", Component);
            writer.WriteObjectValue<ExtensionsPutResponse_data_overlay>("overlay", Overlay);
            writer.WriteObjectValue<ExtensionsPutResponse_data_panel>("panel", Panel);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
