// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace TheOmenDen.CorvidDelivery.Twitch.Extensions.Released {
    public class ReleasedGetResponse_data_icon_urls : IAdditionalDataHolder, IParsable {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The OneZeroZerox100 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OneZeroZerox100 { get; set; }
#nullable restore
#else
        public string OneZeroZerox100 { get; set; }
#endif
        /// <summary>The ThreeZeroZerox200 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ThreeZeroZerox200 { get; set; }
#nullable restore
#else
        public string ThreeZeroZerox200 { get; set; }
#endif
        /// <summary>The TwoFourx24 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TwoFourx24 { get; set; }
#nullable restore
#else
        public string TwoFourx24 { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="ReleasedGetResponse_data_icon_urls"/> and sets the default values.
        /// </summary>
        public ReleasedGetResponse_data_icon_urls() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="ReleasedGetResponse_data_icon_urls"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static ReleasedGetResponse_data_icon_urls CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new ReleasedGetResponse_data_icon_urls();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"100x100", n => { OneZeroZerox100 = n.GetStringValue(); } },
                {"300x200", n => { ThreeZeroZerox200 = n.GetStringValue(); } },
                {"24x24", n => { TwoFourx24 = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("100x100", OneZeroZerox100);
            writer.WriteStringValue("300x200", ThreeZeroZerox200);
            writer.WriteStringValue("24x24", TwoFourx24);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
