// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace TheOmenDen.CorvidDelivery.TiltifyApi.Api.Private.Webhook_relays.Item.Webhook_relay_keys.Item {
    [Obsolete("This class is obsolete. Use WithWebhook_relay_key_GetResponse instead.")]
    public class WithWebhook_relay_key_Response : WithWebhook_relay_key_GetResponse, IParsable {
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="WithWebhook_relay_key_Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new WithWebhook_relay_key_Response CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new WithWebhook_relay_key_Response();
        }
    }
}
