// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
using TheOmenDen.CorvidDelivery.TiltifyApi.Api.Private.Webhook_relays.Item.Webhook_relay_keys;
namespace TheOmenDen.CorvidDelivery.TiltifyApi.Api.Private.Webhook_relays.Item {
    /// <summary>
    /// Builds and executes requests for operations under \api\private\webhook_relays\{webhook_relay_id}
    /// </summary>
    public class WithWebhook_relay_ItemRequestBuilder : BaseRequestBuilder {
        /// <summary>The webhook_relay_keys property</summary>
        public Webhook_relay_keysRequestBuilder Webhook_relay_keys { get =>
            new Webhook_relay_keysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="WithWebhook_relay_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithWebhook_relay_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/private/webhook_relays/{webhook_relay_id}", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new <see cref="WithWebhook_relay_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithWebhook_relay_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/private/webhook_relays/{webhook_relay_id}", rawUrl) {
        }
    }
}
