// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
using TheOmenDen.CorvidDelivery.TiltifyApi.Api.Public.Team_campaigns.By.Slugs.Item;
namespace TheOmenDen.CorvidDelivery.TiltifyApi.Api.Public.Team_campaigns.By.Slugs {
    /// <summary>
    /// Builds and executes requests for operations under \api\public\team_campaigns\by\slugs
    /// </summary>
    public class SlugsRequestBuilder : BaseRequestBuilder {
        /// <summary>Gets an item from the TheOmenDen.CorvidDelivery.TiltifyApi.api.public.team_campaigns.by.slugs.item collection</summary>
        /// <param name="position">Team Slug</param>
        /// <returns>A <see cref="WithTeam_slugItemRequestBuilder"/></returns>
        public WithTeam_slugItemRequestBuilder this[string position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            urlTplParams.Add("team_slug", position);
            return new WithTeam_slugItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>
        /// Instantiates a new <see cref="SlugsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SlugsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public/team_campaigns/by/slugs", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new <see cref="SlugsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SlugsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public/team_campaigns/by/slugs", rawUrl) {
        }
    }
}
