// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
using TheOmenDen.CorvidDelivery.TiltifyApi.Api.Private.Webhook_endpoints;
using TheOmenDen.CorvidDelivery.TiltifyApi.Api.Private.Webhook_enpdoints;
using TheOmenDen.CorvidDelivery.TiltifyApi.Api.Private.Webhook_relays;
namespace TheOmenDen.CorvidDelivery.TiltifyApi.Api.Private {
    /// <summary>
    /// Builds and executes requests for operations under \api\private
    /// </summary>
    public class PrivateRequestBuilder : BaseRequestBuilder {
        /// <summary>The webhook_endpoints property</summary>
        public Webhook_endpointsRequestBuilder Webhook_endpoints { get =>
            new Webhook_endpointsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhook_enpdoints property</summary>
        public Webhook_enpdointsRequestBuilder Webhook_enpdoints { get =>
            new Webhook_enpdointsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhook_relays property</summary>
        public Webhook_relaysRequestBuilder Webhook_relays { get =>
            new Webhook_relaysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="PrivateRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PrivateRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/private", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new <see cref="PrivateRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PrivateRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/private", rawUrl) {
        }
    }
}
