// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace TheOmenDen.CorvidDelivery.TiltifyApi.Api.Public.Team_campaigns.Item.Donor_leaderboards {
    public enum GetTime_typeQueryParameterType {
        [EnumMember(Value = "daily")]
        Daily,
        [EnumMember(Value = "weekly")]
        Weekly,
        [EnumMember(Value = "monthly")]
        Monthly,
        [EnumMember(Value = "yearly")]
        Yearly,
        [EnumMember(Value = "ytd")]
        Ytd,
        [EnumMember(Value = "all")]
        All,
    }
}
