// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
using TheOmenDen.CorvidDelivery.TiltifyApi.Api.Public.Fundraising_events.Item;
namespace TheOmenDen.CorvidDelivery.TiltifyApi.Api.Public.Fundraising_events {
    /// <summary>
    /// Builds and executes requests for operations under \api\public\fundraising_events
    /// </summary>
    public class Fundraising_eventsRequestBuilder : BaseRequestBuilder {
        /// <summary>Gets an item from the TheOmenDen.CorvidDelivery.TiltifyApi.api.public.fundraising_events.item collection</summary>
        /// <param name="position">Fundraising Event ID</param>
        /// <returns>A <see cref="WithFundraising_event_ItemRequestBuilder"/></returns>
        public WithFundraising_event_ItemRequestBuilder this[string position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            urlTplParams.Add("fundraising_event_id", position);
            return new WithFundraising_event_ItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>
        /// Instantiates a new <see cref="Fundraising_eventsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Fundraising_eventsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public/fundraising_events", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new <see cref="Fundraising_eventsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Fundraising_eventsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public/fundraising_events", rawUrl) {
        }
    }
}
