// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
using TheOmenDen.CorvidDelivery.TiltifyApi.Api.Private.Webhook_endpoints.Item.Activate;
using TheOmenDen.CorvidDelivery.TiltifyApi.Api.Private.Webhook_endpoints.Item.Webhook_subscriptions;
namespace TheOmenDen.CorvidDelivery.TiltifyApi.Api.Private.Webhook_endpoints.Item {
    /// <summary>
    /// Builds and executes requests for operations under \api\private\webhook_endpoints\{webhook_endpoint_id}
    /// </summary>
    public class WithWebhook_endpoint_ItemRequestBuilder : BaseRequestBuilder {
        /// <summary>The activate property</summary>
        public ActivateRequestBuilder Activate { get =>
            new ActivateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhook_subscriptions property</summary>
        public Webhook_subscriptionsRequestBuilder Webhook_subscriptions { get =>
            new Webhook_subscriptionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="WithWebhook_endpoint_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithWebhook_endpoint_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/private/webhook_endpoints/{webhook_endpoint_id}", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new <see cref="WithWebhook_endpoint_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithWebhook_endpoint_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/private/webhook_endpoints/{webhook_endpoint_id}", rawUrl) {
        }
    }
}
