// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace TheOmenDen.CorvidDelivery.TiltifyApi.Models {
    /// <summary>The Fitness Goal distance unit if it exists</summary>
    public enum FitnessGoal_distance_unit {
        [EnumMember(Value = "meter")]
        Meter,
        [EnumMember(Value = "kilometer")]
        Kilometer,
        [EnumMember(Value = "mile")]
        Mile,
    }
}
