// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace TheOmenDen.CorvidDelivery.TiltifyApi.Models {
    public enum WebhookSubscription_event_types {
        [EnumMember(Value = "private:direct:donation_updated")]
        PrivateDirectDonation_updated,
        [EnumMember(Value = "private:direct:fact_updated")]
        PrivateDirectFact_updated,
        [EnumMember(Value = "private:indirect:donation_updated")]
        PrivateIndirectDonation_updated,
        [EnumMember(Value = "private:indirect:fact_updated")]
        PrivateIndirectFact_updated,
        [EnumMember(Value = "public:direct:donation_updated")]
        PublicDirectDonation_updated,
        [EnumMember(Value = "public:direct:fact_updated")]
        PublicDirectFact_updated,
        [EnumMember(Value = "public:indirect:donation_updated")]
        PublicIndirectDonation_updated,
        [EnumMember(Value = "public:indirect:fact_updated")]
        PublicIndirectFact_updated,
    }
}
