// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace TheOmenDen.CorvidDelivery.Twitch.Bits.Cheermotes {
    public class CheermotesGetResponse_data_tiers_images : IAdditionalDataHolder, IParsable {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The dark property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public CheermotesGetResponse_data_tiers_images_dark? Dark { get; set; }
#nullable restore
#else
        public CheermotesGetResponse_data_tiers_images_dark Dark { get; set; }
#endif
        /// <summary>The light property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public CheermotesGetResponse_data_tiers_images_light? Light { get; set; }
#nullable restore
#else
        public CheermotesGetResponse_data_tiers_images_light Light { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="CheermotesGetResponse_data_tiers_images"/> and sets the default values.
        /// </summary>
        public CheermotesGetResponse_data_tiers_images() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="CheermotesGetResponse_data_tiers_images"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static CheermotesGetResponse_data_tiers_images CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new CheermotesGetResponse_data_tiers_images();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"dark", n => { Dark = n.GetObjectValue<CheermotesGetResponse_data_tiers_images_dark>(CheermotesGetResponse_data_tiers_images_dark.CreateFromDiscriminatorValue); } },
                {"light", n => { Light = n.GetObjectValue<CheermotesGetResponse_data_tiers_images_light>(CheermotesGetResponse_data_tiers_images_light.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<CheermotesGetResponse_data_tiers_images_dark>("dark", Dark);
            writer.WriteObjectValue<CheermotesGetResponse_data_tiers_images_light>("light", Light);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
