// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace TheOmenDen.CorvidDelivery.Twitch.Guest_star.Channel_settings {
    public class Channel_settingsGetResponse_data : IAdditionalDataHolder, IParsable {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The browser_source_token property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BrowserSourceToken { get; set; }
#nullable restore
#else
        public string BrowserSourceToken { get; set; }
#endif
        /// <summary>The is_browser_source_audio_enabled property</summary>
        public bool? IsBrowserSourceAudioEnabled { get; set; }
        /// <summary>The is_moderator_send_live_enabled property</summary>
        public bool? IsModeratorSendLiveEnabled { get; set; }
        /// <summary>The layout property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Layout { get; set; }
#nullable restore
#else
        public string Layout { get; set; }
#endif
        /// <summary>The slot_count property</summary>
        public double? SlotCount { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="Channel_settingsGetResponse_data"/> and sets the default values.
        /// </summary>
        public Channel_settingsGetResponse_data() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="Channel_settingsGetResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static Channel_settingsGetResponse_data CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new Channel_settingsGetResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"browser_source_token", n => { BrowserSourceToken = n.GetStringValue(); } },
                {"is_browser_source_audio_enabled", n => { IsBrowserSourceAudioEnabled = n.GetBoolValue(); } },
                {"is_moderator_send_live_enabled", n => { IsModeratorSendLiveEnabled = n.GetBoolValue(); } },
                {"layout", n => { Layout = n.GetStringValue(); } },
                {"slot_count", n => { SlotCount = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("browser_source_token", BrowserSourceToken);
            writer.WriteBoolValue("is_browser_source_audio_enabled", IsBrowserSourceAudioEnabled);
            writer.WriteBoolValue("is_moderator_send_live_enabled", IsModeratorSendLiveEnabled);
            writer.WriteStringValue("layout", Layout);
            writer.WriteDoubleValue("slot_count", SlotCount);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
