// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace TheOmenDen.CorvidDelivery.Twitch.Bits.Leaderboard {
    public class LeaderboardGetResponse : IAdditionalDataHolder, IParsable {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<LeaderboardGetResponse_data>? Data { get; set; }
#nullable restore
#else
        public List<LeaderboardGetResponse_data> Data { get; set; }
#endif
        /// <summary>The date_range property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public LeaderboardGetResponse_date_range? DateRange { get; set; }
#nullable restore
#else
        public LeaderboardGetResponse_date_range DateRange { get; set; }
#endif
        /// <summary>The total property</summary>
        public double? Total { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="LeaderboardGetResponse"/> and sets the default values.
        /// </summary>
        public LeaderboardGetResponse() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="LeaderboardGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static LeaderboardGetResponse CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new LeaderboardGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"data", n => { Data = n.GetCollectionOfObjectValues<LeaderboardGetResponse_data>(LeaderboardGetResponse_data.CreateFromDiscriminatorValue)?.ToList(); } },
                {"date_range", n => { DateRange = n.GetObjectValue<LeaderboardGetResponse_date_range>(LeaderboardGetResponse_date_range.CreateFromDiscriminatorValue); } },
                {"total", n => { Total = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<LeaderboardGetResponse_data>("data", Data);
            writer.WriteObjectValue<LeaderboardGetResponse_date_range>("date_range", DateRange);
            writer.WriteDoubleValue("total", Total);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
